version: '3'

services:
  redis:
    image: redis:7.0.5-alpine
    container_name: pay-redis
    networks:
      - pay_network
    ports:
      - "6379:6379"

  mysql:
    image: mysql:8.0
    container_name: pay-mysql
    networks:
      - pay_network
    volumes:
      - ./db/conf.d:/etc/mysql/conf.d
      - ./db/data:/var/lib/mysql
      - ./db/initdb.d:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    env_file: .env

  payment-service:
    image: fcpay-payment-service:0.0.1-SNAPSHOT
    container_name: payment-service
    networks:
      - pay_network
    ports:
      - "8081:8080"
    depends_on:
      - mysql
    env_file: .env

  banking-service:
    image: fcpay-banking-service:0.0.1-SNAPSHOT
    container_name: banking-service
    networks:
      - pay_network
    ports:
      - "8082:8080"
    depends_on:
      - mysql
    env_file: .env

networks:
  pay_network:
    driver: bridge