spring:
  datasource:
    url: 'jdbc:h2:mem:fcPay'
    username: 'user'
    password: ''
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        temp:
    open-in-view: false
  h2:
    console:
      enabled: true
      path: '/h2-console'
      settings:
        web-allow-others: true

server:
  banking-service:
    url: http://localhost:8082