spring:
  datasource:
    url: jdbc:mysql://localhost:3306/pay?useSSL=false&allowPublicKeyRetrieval=true
    username: mysqluser
    password: mysqlpw
    type: com.zaxxer.hikari.HikariDataSource
    driverClassName: com.mysql.cj.jdbc.Driver

  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        temp:
    open-in-view: false
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

server:
  banking-service:
    url: http://localhost:8082